---
title: "First Knit"
author: "Trevor Ragazzo"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer    
I attended Paraclete High School for four years, I graduated in 2021. Now I am a student at Northern Arizona University in flagstaff and I am planing to graduate from there in the year 2025. In high school I hated my English classes and loved math, now being a college student I seem to really enjoy English much more than math. English always seemed to be my hardest subject because I just would not understand some of the curriculum but throughout my four years in high school I never got a lower score than a B. My best subjects always seem to be science related, this is because I do well in subjects that I am interested in. 
  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I use a windows desktop at home, I would say im a 6 when it comes to computers, I know where most things are located. I live in the country side and my WiFi isn't the best, but I will always turn in my work. 
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  My name is Trevor Ragazzo, but people call me Trev, Trevor, and Big Trev. I really dont mind what people call me so you can call whatever you would like. 
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
  My first goal in life is to achieve my college diploma, I should recieve this less than 3 years from now. I really want to get more interested in Forestry (This is the major I am taking at NAU) I am trying to recieve a science degree in forestry.   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   The only foreign country I have been to was Mexico, I go everyone the day after Christmas for a small vacation. I really want to travel to Japan, and different places in Europe. I have not been in the military but I have thought of joining before. If I could choose I would be in the Air Force just because I know people in the Air Force and it seems the safest. 
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  First and foremost this is my first math class at AVC, and I need it as a pre req for forestry classes at NAU. But I have taken math classes at NAU such as PRE-CALC and Algebra for Calc. ALso for NAU this class is transferable for my major forestry.My plan is to get and A in this class and to understand stats.  
   
 






  




